[build]
  command = "yarn build"
  publish = "dist"
  functions = "lambda"


# created in part using CSP Generator extension (csper.io)
# hash obtained by console error or using https://report-uri.com/home/hash, delete only the <script></script> tags, keeping whitespace
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = '''
      default-src 'self';
      script-src 'self' 'sha256-dK06Ziaa0EW7eznMaLyuarFhVcusz+7eBUuwXo3gWD8=' https://js.stripe.com/v3/ https://www.google-analytics.com/analytics.js https://www.googletagmanager.com/gtag/js;
      style-src 'self';
      object-src 'none';
      base-uri 'self';
      connect-src 'self' https://api.pushshift.io https://api.revddit.com https://oauth.reddit.com https://ored.reveddit.com https://rviewit.com https://www.reddit.com;
      font-src 'self';
      frame-src 'self' https://js.stripe.com;
      img-src 'self' data: https:;
      manifest-src 'self';
      media-src 'self';
      worker-src 'none';
    '''
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[[headers]]
  for = "/images/*"

  [headers.values]
    cache-control = '''
    public,
    max-age=604800'''

[[headers]]
  for = "/*.js"

  [headers.values]
    cache-control = '''
    public,
    max-age=604800'''

[[headers]]
  for = "/*.css"

  [headers.values]
    cache-control = '''
    public,
    max-age=604800'''
