[build]
  command = "yarn build"
  publish = "dist"
  functions = "lambda"

[[headers]]
  for = "/images/*"

  [headers.values]
    cache-control = '''
    public,
    max-age=604800'''

#[[headers]]
#  for = "/*.js"
#
#  [headers.values]
#    cache-control = '''
#    public,
#    max-age=604800'''
#
#[[headers]]
#  for = "/*.css"
#
#  [headers.values]
#    cache-control = '''
#    public,
#    max-age=604800'''
